name: linting, testing, building
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
permissions:
  contents: write
  pages: write
  id-token: write
  actions: write 
  deployments: write 
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      deployments: write
    steps:
      - name: Delete Deployment Environment
        uses: strumwolf/delete-deployment-environment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: github-pages
          onlyRemoveDeployments: true

  build-and-ui-unit-testing:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} 
    permissions:
      contents: read 
      pages: write  
      id-token: write 
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build production project
        run: npm run build:prod
      - name: Build storybook
        run: npm run storybook:build
      - name: Run screenshot testing
        run: npm run test:ui:ci
      - name: Run unit tests
        run: npm run test:unit
        if: always()
      - name: Generate HTML report
        run: npm run test:ui:report
        if: always()
      - name: move loki
        run: mv .loki reports/
        if: always()
      - name: move storybook
        run: mv storybook-static reports/storybook
        if: always()
      - name: Setup Pages
        uses: actions/configure-pages@v5
        if: always()
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'reports'
          name: 'github-pages' 
        if: always()
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        if: always()

  checks-linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci --force
      - name: Lint TypeScript
        run: npm run lint:ts
        if: always()
      - name: Lint CSS/SCSS
        run: npm run lint:scss